fastlane_version "2.28.6"

default_platform :ios

platform :ios do

  desc "Increments the build number, submits this new version to TestFlight and commits the version bump"
  lane :beta do
    # Sync certificates and provisioning profiles for Release
    match(type: "appstore")
    # Increase by 1 the build number
    increment_build_number(xcodeproj: './ios/animations.xcodeproj')
    # Compile, build and export IPA in Release
    gym(scheme: "animations", project: "./ios/animations.xcodeproj", output_name: "animations.ipa", clean: true)
    # Upload build to TestFlight
    pilot(skip_waiting_for_build_processing: true)
    # git commit the version increase
    commit_version_bump(
      message: "Deployed new build #{lane_context[SharedValues::BUILD_NUMBER]}",
      xcodeproj: './ios/animations.xcodeproj'
    )
  end

  desc "Exports an ipa file to the project root directory named animations.ipa"
  lane :dev do
    # Sync certificates and provisioning profiles for Debug
    match(type: "development")
    # Compile, build and export IPA in Debug
    gym(
      scheme: "animations",
      project: "./ios/animations.xcodeproj",
      output_name: "animations.ipa",
      clean: true,
      configuration: 'Debug'
    )
  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   match(type: "appstore")
  #   # snapshot
  #   gym(scheme: "animations", project: "./ios/animations.xcodeproj") # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

end
